CREATE TABLE [dbo].[Table1]
(
	[id] INT NOT NULL PRIMARY KEY, 
    [course] INT NOT NULL DEFAULT 0, 
    [name] CHAR(255) NOT NULL, 
    [scormtype] CHAR(50) NOT NULL DEFAULT 'local', 
    [reference] CHAR(255) NOT NULL, 
    [intro] TEXT NOT NULL, 
    [introformat] INT NOT NULL DEFAULT 0, 
    [version] CHAR(9) NOT NULL, 
    [maxgrade] FLOAT NOT NULL DEFAULT 0, 
    [grademethod] INT NOT NULL DEFAULT 0, 
    [whatgrade] INT NOT NULL DEFAULT 0, 
    [maxattempt] INT NOT NULL DEFAULT 1, 
    [forcecompleted] INT NOT NULL DEFAULT 0, 
    [forcenewattempt] INT NOT NULL DEFAULT 0, 
    [lastattemptblock] INT NOT NULL DEFAULT 0, 
    [displayattemptstatus] INT NOT NULL DEFAULT 1, 
    [displaycoursestructure] INT NOT NULL DEFAULT 0, 
    [updatefreq] INT NOT NULL DEFAULT 0, 
    [sha1hash] CHAR(40) NULL, 
    [md5hash] CHAR(32) NOT NULL, 
    [revision] INT NULL DEFAULT 0, 
    [launch] INT NULL DEFAULT 0, 
    [skipview] INT NULL DEFAULT 1, 
    [hidebrowse] INT NULL DEFAULT 0, 
    [hidetoc] INT NULL DEFAULT 0, 
    [nav] INT NULL DEFAULT 1, 
    [navpositionleft] INT NULL DEFAULT -100, 
    [navpositiontop] INT NULL DEFAULT -100, 
    [auto] INT NOT NULL DEFAULT 0, 
    [popup] INT NOT NULL DEFAULT 0, 
    [options] CHAR(255) NOT NULL, 
    [width] INT NOT NULL DEFAULT 100, 
    [height] INT NOT NULL DEFAULT 600, 
    [timeopen] INT NOT NULL DEFAULT 0, 
    [timeclose] INT NOT NULL DEFAULT 0, 
    [timemodified] INT NOT NULL DEFAULT 0, 
    [completionstatusrequired] INT NULL, 
    [completionscorerequired] INT NULL, 
    [displayactivityname] INT NULL, 
    [autocommit] INT NOT NULL 
)
