CREATE TABLE [dbo].[Table3]
(
	[id] INT NOT NULL PRIMARY KEY, 
    [course] INT NOT NULL DEFAULT 0, 
    [name] CHAR(255) NOT NULL, 
    [intro] TEXT NOT NULL , 
    [introformat] INT NOT NULL DEFAULT 0, 
    [timeopen] INT NOT NULL DEFAULT 0, 
    [timeclose] INT NOT NULL DEFAULT 0, 
    [timelimit] INT NOT NULL DEFAULT 0, 
    [overduehandling] CHAR(16) NOT NULL DEFAULT 'autoabandon', 
    [graceperiod] INT NOT NULL DEFAULT 0, 
    [preferredbehaviour] CHAR(32) NOT NULL , 
    [canredoquestions] INT NOT NULL DEFAULT 0, 
    [attempts] INT NOT NULL DEFAULT 0, 
    [attemptonlast] INT NOT NULL DEFAULT 0, 
    [grademethod] INT NOT NULL DEFAULT 1, 
    [decimalpoints] INT NOT NULL DEFAULT 2, 
    [questiondecimalpoints] INT NOT NULL DEFAULT -1, 
    [reviewattempt] INT NOT NULL DEFAULT 0, 
    [reviewcorrectness] INT NOT NULL DEFAULT 0, 
    [reviewmarks] INT NOT NULL DEFAULT 0, 
    [reviewspecificfeedback] INT NOT NULL DEFAULT 0, 
    [reviewgeneralfeedback] INT NOT NULL DEFAULT 0, 
    [reviewrightanswer] INT NOT NULL DEFAULT 0, 
    [reviewoverallfeedback] INT NOT NULL DEFAULT 0, 
    [questionsperpage] INT NOT NULL DEFAULT 0, 
    [navmethod] CHAR(16) NOT NULL DEFAULT 'free', 
    [shuffleanswers] INT NOT NULL DEFAULT 0, 
    [sumgrades] NUMERIC(10, 5) NOT NULL DEFAULT 0, 
    [grade] NUMERIC(10, 5) NOT NULL DEFAULT 0, 
    [timecreated] INT NOT NULL DEFAULT 0, 
	[timemodified] INT NOT NULL DEFAULT 0,
    [password] CHAR(255) NOT NULL , 
    [subnet] CHAR(255) NOT NULL , 
    [browsersecurity] CHAR(32) NOT NULL , 
    [delay1] INT NOT NULL DEFAULT 0, 
    [delay2] INT NOT NULL DEFAULT 0, 
    [showuserpicture] INT NOT NULL DEFAULT 0, 
    [showblocks] INT NOT NULL DEFAULT 0, 
    [completionattemptsexhausted] INT NULL DEFAULT 0, 
    [completionpass] INT NULL DEFAULT 0 
)
