CREATE TABLE [dbo].[Table4]
(
	[id] INT NOT NULL PRIMARY KEY  , 
    [course] INT NOT NULL DEFAULT 0, 
    [name] CHAR(255) NOT NULL, 
    [intro] TEXT NOT NULL, 
    [introformat] INT NOT NULL DEFAULT 0, 
    [alwaysshowdescription] INT NOT NULL DEFAULT 0, 
    [nosubmissions] INT NOT NULL DEFAULT 0, 
    [submissiondrafts] INT NOT NULL DEFAULT 0, 
    [sendnotifications] INT NOT NULL DEFAULT 0, 
    [sendlatenotifications] INT NOT NULL DEFAULT 0, 
    [duedate] INT NOT NULL DEFAULT 0, 
    [allowsubmissionsfromdate] INT NOT NULL DEFAULT 0, 
    [grade] INT NOT NULL DEFAULT 0, 
    [timemodified] INT NOT NULL DEFAULT 0, 
    [requiresubmissionstatement] INT NOT NULL DEFAULT 0, 
    [completionsubmit] INT NOT NULL DEFAULT 0, 
    [cutoffdate] INT NOT NULL DEFAULT 0, 
    [teamsubmission] INT NOT NULL DEFAULT 0, 
    [requireallteammemberssubmit] INT NOT NULL DEFAULT 0, 
    [teamsubmissiongroupingid] INT NOT NULL DEFAULT 0, 
    [blindmarking] INT NOT NULL DEFAULT 0, 
    [revealidentities] INT NOT NULL DEFAULT 0, 
    [attemptreopenmethod] CHAR(10) NOT NULL DEFAULT 'none', 
    [maxattempts] INT NOT NULL DEFAULT -1, 
    [markingworkflow] INT NOT NULL DEFAULT 0, 
    [markingallocation] INT NOT NULL DEFAULT 0, 
    [sendstudentnotifications] INT NOT NULL DEFAULT 1, 
    [preventsubmissionnotingroup] INT NOT NULL DEFAULT 0
)
